module.exports = {
  changes: require('./changes'),
  changeHistory: require('./changeHistory'),
  compute: require('./compute').compute,
  createInstance: require('./createInstance'),
  defineResource: require('./defineResource'),
  digest: require('./digest'),
  eject: require('./eject'),
  ejectAll: require('./ejectAll'),
  filter: require('./filter'),
  get: require('./get'),
  hasChanges: require('./hasChanges'),
  inject: require('./inject'),
  lastModified: require('./lastModified'),
  lastSaved: require('./lastSaved'),
  link: require('./link'),
  linkAll: require('./linkAll'),
  linkInverse: require('./linkInverse'),
  previous: require('./previous'),
  unlinkInverse: require('./unlinkInverse')
};
